lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
markdown: kramdown
title: "AL-Go for GitHub"
description: "The plug-and-play DevOps solution for Business Central app development on GitHub"
baseurl: AL-Go/
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-responsive_image
